services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  task-svc:
    image: bazucas/task-svc:latest
    build: 
      context: .
      dockerfile: src/API/VL.Taskio.TaskService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 3010:80
  identity-svc:
    image: bazucas/identity-svc:latest
    build: 
      context: .
      dockerfile: src/API/VL.Taskio.IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5010:80
    depends_on:
      - postgres
  gateway-svc:
    image: bazucas/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/API/VL.Taskio.GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6010:80